### PR TITLE
#40 [CompetitorPrice] fix: sql bug of setCategories

### LINKED ISSUE #40: Erreur SQL

### PR DESCRIPTION
**Pull request by evarisk-charles**

### CODE REVIEW

File: view/competitorprice_card.php [hunk 1]
```diff
@@ -186,6 +186,7 @@
     }
 
     $noback = 1;
+    $object->setCategories('setCategories');
```
Comment (nicolas-eoxia) [inline view/competitorprice_card.php]: inutile
